### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by zcdliuwei** [JourneyDB/JourneyDB#1]
Thank you for sharing ！！
May I ask which version of Midjourney these pictures come from? V3, V4, or V5?

**Comment by KeqiangSun** [comment]
Thanks for your inquiry. We use V4 and V5, which are identified by filtering based on timestamps and prompt keywords.

**Comment by zcdliuwei** [comment]
> Thanks for your inquiry. We use V4 and V5, which are identified by filtering based on timestamps and prompt keywords.

thanks!
