### ISSUE TITLE
Can not download the data

### ISSUE THREAD

**Issue by oubi2015** [JourneyDB/JourneyDB#3]
This link has expired:
https://mega.nz/#P!AgC1ikBVhBOJxS6y5-VQQJzcxe51wNvbekggbW8_AjgByqvYeIxcX0skT2Hlub6PjZXBKUkEBfDQijLNkMFwNecvKnQc6_vgHpoWWcv2LW0139Y1NM0ugQ

What should I do?

**Comment by KeqiangSun** [comment]
I can open this link without any problem. Could you please screenshot the error?

**Comment by KeqiangSun** [comment]
The link is working well. Users in other issues have downloaded the data successfully. Please check your network settings if you still have the problem.
For easier acquirement, we are working actively to upload the data to other platforms like HuggingFace. Stay tuned!

**Comment by KeqiangSun** [comment]
I will close this issue since users in other issues have downloaded the data successfully. Please feel free if you have further problems.
